### ISSUE TITLE
Which Resistors R104, R103 needed for CTI OC5SC25

### ISSUE THREAD

**Issue by davrad3** [paulvee/Lars-GPSDO-V4.2#2]
Hi Paul,
did you also check the CTI OCXO for its sweetspot? As far as i interpreted your schematic the values are for the Bliley only.
Thanks a lot in advance!!

**Comment by paulvee** [comment]
@davrad3, have a look at earlier blogposts like the Version 3 and earlier for information/values for other OCXO's I used and tested.
